### ISSUE TITLE
Update Accelerometer Description

### ISSUE THREAD

**Issue by bosco662607** [marqsw/Sensors#3]
In the app, it says "It detects forces such as gravity, vibration, and movement.", but vibration and movement aren't forces.

**Comment by bosco662607** [comment]
Also the accelerometer detects the acceleration, rather than the force.

**Comment by marqsw** [comment]
Thank you. The description would be changed to "An accelerometer measures the acceleration. It detects gravity, vibration, and movement." in the next version. Please feel free to create a new issue if you find another error in the descriptions 😊
