### ISSUE TITLE
Renaming Gyroscopic Sensor

### ISSUE THREAD

**Issue by bosco662607** [marqsw/Sensors#4]
A gyroscope is used to maintain orientation rather than measuring. I guess you mean a gyroscopic sensor here.

**Comment by marqsw** [comment]
Thanks. It is indeed a gyroscopic sensor, just as barometric sensor is called barometer. The name gyroscope is used in [Expo documentation](https://docs.expo.dev/versions/latest/sdk/gyroscope/), and in another a similar [app made by Kelvin Choi](https://www.tszheichoi.com/sensorlogger). It is also a shorter name compared to gyroscopic sensor, helps with reducing the chances of clipping on smaller screens.
